# Generated by Django 3.0.1 on 2020-05-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='顶部图片'),
        ),
    ]
