# Generated by Django 3.0.1 on 2020-05-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TalkRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('talk', models.CharField(max_length=256, null=True, blank=True, verbose_name='请求')),
                ('result', models.CharField(max_length=256, null=True, blank=True, verbose_name='回复')),
                ('user_id', models.IntegerField(null=True, blank=True, verbose_name='用户ID'),),
                ('user_ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户IP')),
                ('username', models.CharField(blank=True, max_length=10, null=True, verbose_name='用户名称')),
            ],
            options={
                'verbose_name': '对话记录',
                'verbose_name_plural': '对话记录',
            },
        ),
    ]
